architecture:
   name: TristouNet
   params:
     rnn: LSTM
     recurrent: [16]
     mlp: [16, 16]
     bidirectional: concat

approach:
   name: TripletLoss
   params:
     metric: euclidean
     margin: 0.1
     clamp: positive
     per_batch: 1
     per_fold: 20
     per_label: 10
     gradient_factor: 10000
     batch_size: 128
